# Generated by Django 3.2.7 on 2021-09-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='old_price',
            field=models.IntegerField(default=0),
        ),
    ]
