# Generated by Django 4.0.1 on 2022-01-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_order_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
