# Generated by Django 4.0.1 on 2022-01-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
