# Generated by Django 4.0.1 on 2022-01-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('com', models.CharField(max_length=100)),
            ],
        ),
    ]
